### PR TITLE
ZIO 2.0.0-RC3

### PR DESCRIPTION
**Pull request by vigoo**
Remaining dependencies:
- [ ] zio-nio (https://github.com/zio/zio-nio/pull/484)
- [ ] zio-telemetry (https://github.com/zio/zio-telemetry/pull/509)

### CODE REVIEW

**Comment by vigoo** [comment]
Seems like I did not properly compile it locally, will fix

**Comment by adamw** [comment]
maybe we need a rc3 release of sttp-shared as well?

**Comment by Pask423** [comment]
ok, I will try to make release today or on tomorrow morning

**Comment by Pask423** [comment]
sttp-shared for rc3 released https://github.com/softwaremill/sttp-shared/releases/tag/v1.3.3

**Comment by vladimir-lu** [comment]
https://github.com/zio/zio-telemetry/releases/tag/v2.0.0-RC2 is out now (should be out of sonatype staging soon I hope)

**Pull request merged**
