### PR TITLE
Update fs2 to 1.0.0

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by kubukoz** [comment]
That was fast @adamw 😂 sorry for breaking the build now, but I think it'll go green on master

**Comment by adamw** [comment]
no worries, it fails occasionally due to some bug in scalajs - selenium integraiton

**Comment by kubukoz** [comment]
Green! Can you make a release?

**Comment by adamw** [comment]
Done in 1.3.9 :)

**Comment by adamw** [comment]
Sorry, 1.3.8

**Pull request merged**
