### PR TITLE
added response size summary metric

### PR DESCRIPTION
**Pull request by mrForest13**
I added a response size metric. Can be useful in some cases

### CODE REVIEW

**Comment by adamw** [comment]
Thanks! There seem to be some compilation errors, though

**Comment by mrForest13** [comment]
There is any reason why you import `import scala.collection.immutable.Seq` in `sttp.client3.Response`? Why not just use `Seq`? (by that i mean remove import)

> [error] /home/runner/work/sttp/sttp/metrics/prometheus-backend/src/test/scala/sttp/client3/prometheus/PrometheusBackendTest.scala:252:59: type mismatch;
[error]  found   : Seq[sttp.model.Header]
[error]  required: scala.collection.immutable.Seq[sttp.model.Header]
[error]     val response = Response("Ok", StatusCode.Ok, "Ok", Seq(Header.contentLength(10)))
[error]                                                           ^
[error] one error found

**Comment by adamw** [comment]
Because in Scala 2.12 and earlier, `Seq` was an alias for `import scala.collection.Seq` (which includes mutable and immutable ones). In 2.13+, this changed to `import scala.collection.immutable.Seq`.

**Comment by mrForest13** [comment]
it makes sense, thanks

**Comment by adamw** [comment]
Thanks as well :)

**Pull request merged**
