### PR TITLE
Scalajs 1.0.1

### PR DESCRIPTION
**Pull request by cheleb**
As monix is not (yet) available for scala js 1.0.1 I had to comment out monixJS.

This PR pr also depends on sttp-model  takayahilton/scalajs-1.0.1 update

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Seems monix is almost ready, pending a release: https://github.com/monix/monix/pull/1157

**Comment by adamw** [comment]
If somebody would wonder, if "delete" removes a file from the PR, or removes the file inside the PR, it's the latter ;-)

**Comment by adamw** [comment]
Merged separately

**Comment by adamw** [comment]
Released in 2.1.0-RC1. Thanks! :)

**Pull request closed without merging**
