### PR TITLE
Drop java8-compat dependency

### PR DESCRIPTION
**Pull request by Pask423**
There is a problem with conflicting cross-version for java8-compat dependency on scala-3.
In fact we only a few converters so I deiced to write our own converters for sttp and drop whole dependency.

### CODE REVIEW

**Comment by adamw** [comment]
Thanks!

**Comment by loicdescotte** [comment]
Hi,
Unfortunately we are still using Java 8 for some clients, if I understand correctly, the problem is with Scala 3, would it be possible to keep java 8 support for Scala 2.13?
I know it's not offically supported anymore, but it would be really great... Thanks!

**Comment by adamw** [comment]
Sorry, I doubt it, we've included the HttpClient-based client in the `core` module (this is now the default backend). And that implementation is only available with Java11+, so we need to compile using Java 11.

If you really need this, maybe you can try backporting zio2 support to 3.5.x. If you'll have a working branch, I can release it as the next 3.5.x patch release.

**Comment by adamw** [comment]
I've created a 3.5 branch from the latest 3.5 release: https://github.com/softwaremill/sttp/tree/3.5

**Comment by loicdescotte** [comment]
> If you really need this, maybe you can try backporting zio2 support to 3.5.x. If you'll have a working branch, I can release it as the next 3.5.x patch release.

Thanks I will try this, that would be great!

**Pull request merged**
