### PR TITLE
Add Pekko support

### PR DESCRIPTION
**Pull request by benjamingeer**
Before submitting pull request:
- [ ] Check if the project compiles by running `sbt compile`
- [ ] Verify docs compilation by running `sbt compileDocs`
- [ ] Check if tests pass by running `sbt test`
- [ ] Format code by running `sbt scalafmt`

### CODE REVIEW

**Comment by kciesielski** [comment]
@benjamingeer could you bump to https://github.com/apache/incubator-pekko/releases/tag/v1.0.0-rc1?

**Comment by pjfanning** [comment]
is this the same as #1781 ?

**Comment by adamw** [comment]
Yes I think so, though we are still waiting for a publicly available pekko release (non-snapshot)

**Comment by kciesielski** [comment]
Closing in favor of https://github.com/softwaremill/sttp/pull/1781

**Pull request closed without merging**
