### PR TITLE
Add support for cats effect with AHC backend

### PR DESCRIPTION
**Pull request by aeons**

### CODE REVIEW

**Comment by adamw** [comment]
Looks good! Maybe you would like to add yourself to the credits in the readme?

**Comment by aeons** [comment]
Updated readme.

I have a version for fs2 with streaming as well, but there's some dependencies I need to sort out first.

**Comment by adamw** [comment]
Ok, I'll merge this and then we can work on fs2 in a separate PR

Thanks for the contribution!

**Comment by adamw** [comment]
Released in 0.0.5

**Pull request merged**
