### PR TITLE
#1339 support both in isWebSocket

### PR DESCRIPTION
**Pull request by jkobejs**
#1339 support both in isWebSocket

### CODE REVIEW

**Comment by Pask423** [comment]
There seems to be some errors in `JVM` tests could you fix them?
Apart of this it looks good to me

**Comment by jkobejs** [comment]
I see them on master branch too, I'll see what I can do

**Comment by jkobejs** [comment]
There are 7 failed tests, all of them are related to `should return compressed data` and zio
```
[error] (armeriaBackendZio13 / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (asyncHttpClientBackendZio13 / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (asyncHttpClientBackendZio12_12 / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (asyncHttpClientBackendZio1 / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (armeriaBackendZio1 / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (asyncHttpClientBackendZio12_11 / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (armeriaBackendZio12_12 / Test / test) sbt.TestsFailedException: Tests unsuccessful
```
```
 - should return compressed data *** FAILED *** (120 milliseconds)
[info]   "[34ddc0e65b780bb325f05d8b1eca296]e" was not equal to "[19dfb5e5c761d3a2c9b36cfcdafe24d]e" (HttpTestExtensions.scala:261)
[info]   Analysis:
[info]   "[34ddc0e65b780bb325f05d8b1eca296]e" -> "[19dfb5e5c761d3a2c9b36cfcdafe24d]e"
[info]   + Test: download file should return compressed data, failed with: "[34ddc0e65b780bb325f05d8b1eca296]e" was not equal to "[19dfb5e5c761d3a2c9b36cfcdafe24d]e", retrying. 
```

**Comment by Pask423** [comment]
hmm I thought that they are not the same tests sorry, my bad

**Comment by Pask423** [comment]
closes #1339

**Review by Pask423 — APPROVED** [review]

**Comment by Pask423** [comment]
Thanks!

**Pull request merged**
