### PR TITLE
Bump zio-json

### PR DESCRIPTION
**Pull request by ioleo**
Before submitting pull request:
- [x] Check if the project compiles by running `sbt compile`
- [x] Verify docs compilation by running `sbt compileDocs`
- [x] Check if tests pass by running `sbt test`
- [x] Format code by running `sbt scalafmt`

### CODE REVIEW

**Comment by ioleo** [comment]
The failing test depends on internet, perhaps we can rerun it?

**Comment by adamw** [comment]
Sure, this happens :) I'll get to those flaky tests one day ...

**Comment by ioleo** [comment]
@adamw when you merge it, can you cut a patch release?

**Comment by adamw** [comment]
Release in progress :)

**Pull request merged**
