### PR TITLE
Add libcrypto MD5 digest to Scala Native

### PR DESCRIPTION
**Pull request by lolgab**
This PR adds support for MD5 digest to Scala Native backend based on libcrypto (part of openssl).
It allows to move `DigestAutenticatorTest.scala` to the shared directory.

### CODE REVIEW

**Comment by lolgab** [comment]
Travis seems to fail in a unrelated test.

**Comment by lolgab** [comment]
Thank you very much for merging :)

**Comment by adamw** [comment]
Released in 2.0.10, thanks!

**Comment by adamw** [comment]
Sorry, 2.0.9 :)

**Pull request merged**
