### PR TITLE
Update ZIO to 1.0.0-RC18

### PR DESCRIPTION
**Pull request by ghostdogpr**
Update ZIO to 1.0.0-RC18.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
I think this is ready to merge now. The failing test in CI doesn't seem related.

**Comment by ikryvorotenko** [comment]
Do you have plans to release this? It looks like 2.0.2 still uses 0.17-RC

**Comment by adamw** [comment]
yes, give me a couple of hours, I just merged this 2 hrs ago ;)

**Comment by adamw** [comment]
Released in 2.0.3. See also: https://sttp.softwaremill.com/en/latest/backends/zio.html#zio-environment

**Pull request merged**
